version: "3.9"

services:
  ci_runner:
    build: .
    container_name: backend_api_ci
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Zugriff auf andere Container
    restart: "no"
