version: "3.9"

services:
  github_runner:
    build: .
    container_name: git_runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root   # 🧠 Wichtig! root oder explizit Zugriff auf den Socket erlauben      
    restart: unless-stopped
