name: CI-Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, ci]  # <- Dein Docker-Runner!
    steps:
      - name: Repo auschecken
        uses: actions/checkout@v3

      - name: NodeJS vorbereiten
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Deployment-Skript starten
        run: /deploy.sh
